# Generated by Django 5.2.4 on 2026-04-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='client',
            name='mot_de_passe',
            field=models.CharField(max_length=255),
        ),
    ]
