# Generated by Django 5.2.4 on 2026-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Boké', 'Boké'), ('Kindia', 'Kindia'), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Labé', 'Labé'), ('Faranah', 'Faranah'), ('Kankan', 'Kankan'), ('Nzérékoré', 'Nzérékoré'), ('Kamsar', 'Kamsar'), ('Siguiri', 'Siguiri')], default='Conakry', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='ville',
            field=models.CharField(choices=[('Conakry', 'Conakry'), ('Boké', 'Boké'), ('Kindia', 'Kindia'), ('Boké', 'Boké'), ('Mamou', 'Mamou'), ('Labé', 'Labé'), ('Faranah', 'Faranah'), ('Kankan', 'Kankan'), ('Nzérékoré', 'Nzérékoré'), ('Kamsar', 'Kamsar'), ('Siguiri', 'Siguiri')], default='Conakry', max_length=50),
        ),
    ]
