# Generated by Django 5.2.4 on 2026-04-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_client_ville_alter_vendeur_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='ville',
            field=models.CharField(default='Conakry', max_length=50),
        ),
    ]
