# Generated by Django 5.2.4 on 2026-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendeur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré')], default='actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('non_actif', 'Non actif')], default='non_actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='statut',
            field=models.CharField(choices=[('non_actif', 'Non actif'), ('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='non_actif', max_length=20),
        ),
    ]
