# Generated by Django 5.2.4 on 2026-04-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_client_date_inscription_remove_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='telephone',
            new_name='numero_client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='description',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ville',
        ),
        migrations.AddField(
            model_name='commande',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='ville_client',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
