# Generated by Django 5.2.4 on 2026-04-14 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_commande_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('gratuit', 'Gratuit'), ('essentiel', 'Essentiel'), ('pro', 'Pro'), ('business', 'Business')], max_length=20, unique=True)),
                ('prix', models.IntegerField(default=0)),
                ('limite_produits', models.IntegerField(default=5)),
                ('duree_jours', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='type_abonnement',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('essai', 'Essai gratuit'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], default='essai', max_length=20),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='vendeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='core.vendeur'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planabonnement'),
        ),
    ]
