# Generated by Django 5.2.4 on 2026-04-16 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(max_length=20)),
                ('montant', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planabonnement')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_numero', models.CharField(max_length=20)),
                ('raison', models.CharField(choices=[('arnaque', 'Arnaque'), ('produit_non_conforme', 'Produit non conforme'), ('mauvais_service', 'Mauvais service'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.vendeur')),
            ],
        ),
    ]
