# Generated by Django 5.2.4 on 2026-04-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vendeur_verifie_paiementabonnement_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='ventes_du_mois',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaiementCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paiement', models.CharField(max_length=20)),
                ('montant', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='core.commande')),
            ],
        ),
    ]
