# Generated by Django 5.2.4 on 2026-04-17 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vendeur_ventes_du_mois_paiementcommande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icone', models.CharField(default='📦', max_length=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_envoi',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='lu',
            new_name='lue',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='contenu',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='destinataire_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_notification',
        ),
        migrations.AddField(
            model_name='client',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='2026-17-04', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('commande', 'Commande'), ('abonnement', 'Abonnement'), ('message', 'Message'), ('securite', 'Sécurité'), ('systeme', 'Système')], default='systeme', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='raison_suspension',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.categorie'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_numero', models.CharField(max_length=20)),
                ('note', models.IntegerField(default=5)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('commandee', 'Commandée'), ('payee', 'Payée'), ('acceptee', 'Acceptée par le vendeur'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='core.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'unique_together': {('client', 'produit')},
            },
        ),
    ]
