# Generated by Django 5.2.4 on 2026-04-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categorie_rename_date_envoi_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_debut_promo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_fin_promo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='jours_promo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
