# Generated by Django 5.2.4 on 2026-04-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produit_date_debut_promo_produit_date_fin_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_unitaire',
            field=models.IntegerField(default=0),
        ),
    ]
