# Generated by Django 5.2.4 on 2026-04-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_commande_prix_total_commande_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendeurs/'),
        ),
    ]
