# Generated by Django 5.2.4 on 2026-04-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_vendeur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='dernier_reset_ventes',
            field=models.DateField(blank=True, null=True),
        ),
    ]
