# Generated by Django 5.2.4 on 2026-04-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vendeur_dernier_reset_ventes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='total_produits_crees',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MessageNegociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_numero', models.CharField(max_length=20)),
                ('prix_propose', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('reponse_vendeur', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('contre_offre', 'Contre-offre')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociations', to='core.produit')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendeur')),
            ],
        ),
    ]
