# Generated by Django 5.2.4 on 2026-06-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_commande_archivee_vendeur_total_produits_crees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('non_actif', 'Non actif'), ('actif', 'Actif'), ('expire', 'Expiré'), ('suspendu', 'Suspendu')], default='non_actif', max_length=20),
        ),
    ]
