# Generated by Django 5.2.4 on 2026-06-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_paiementpanier_commande_paiement_panier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('vendeur', 'Vendeur'), ('client', 'Client')], default='client', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('prix_propose', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negociation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.messagenegociation')),
            ],
        ),
    ]
