# Generated by Django 5.2.4 on 2026-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcommande',
            name='mode_paiement',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('carte_bancaire', 'Carte Bancaire'), ('paiement_livraison', 'Paiement à la livraison'), ('virement_bancaire', 'Virement bancaire')], default='orange_money', max_length=30),
        ),
    ]
