# Generated by Django 5.2.4 on 2026-06-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paiementcommande_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenegociation',
            name='client_lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagenegociation',
            name='vendor_lu',
            field=models.BooleanField(default=False),
        ),
    ]
