# Generated by Django 5.2.4 on 2026-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_messagenegociation_client_lu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenegociation',
            name='vendor_lu',
            field=models.BooleanField(default=False),
        ),
    ]
