# Generated by Django 5.2.4 on 2026-06-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_vendor_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementpanier',
            name='mode_paiement',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire'), ('paiement_livraison', 'Paiement à la livraison'), ('virement_bancaire', 'Virement bancaire')], default='orange_money', max_length=30),
        ),
    ]
