# Generated by Django 5.2.4 on 2026-06-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_paiementpanier_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='date_certification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='date_demande_certification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='demande_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='est_certifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='nb_evaluations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='note_confiance',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='AlertePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_nom', models.CharField(max_length=100)),
                ('marque', models.CharField(blank=True, max_length=50)),
                ('prix_cible', models.IntegerField()),
                ('ville', models.CharField(blank=True, max_length=50)),
                ('notifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_prix', to='core.client')),
                ('produit_correspondant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_numero', models.CharField(max_length=20)),
                ('note', models.IntegerField(default=5)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_flash', models.IntegerField()),
                ('quantite_disponible', models.PositiveIntegerField(default=1)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('est_active', models.BooleanField(default=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendeur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sales', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='GarantieAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_numero', models.CharField(max_length=20)),
                ('montant_original', models.IntegerField()),
                ('montant_rembourse', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('utilisee', 'Utilisée'), ('expiree', 'Expirée'), ('refusee', 'Refusée')], default='active', max_length=20)),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantie', to='core.commande')),
            ],
        ),
    ]
