# Generated by Django 5.2.4 on 2026-06-30 12:19

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_vendeur_date_certification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', validators=[core.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(upload_to='produits/', validators=[core.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendeurs/', validators=[core.validators.validate_secure_image]),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField()),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
