# Generated by Django 5.2.4 on 2026-07-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_produit_marque_alter_client_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FideliteClientVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandes_count', models.IntegerField(default=0)),
                ('depenses_total', models.IntegerField(default=0)),
                ('reduction_pct', models.IntegerField(default=0)),
                ('dernier_achat', models.DateTimeField(blank=True, null=True)),
                ('validite_jusqua', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_fidelites', to='core.client')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_fidelites', to='core.vendeur')),
            ],
            options={
                'ordering': ['-commandes_count', '-dernier_achat'],
                'unique_together': {('vendeur', 'client')},
            },
        ),
    ]
