# Generated by Django 5.2.4 on 2026-07-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_fideliteclientvendeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_vendor', 'Connexion vendeur'), ('login_client', 'Connexion client'), ('logout', 'Déconnexion'), ('signup_vendor', 'Inscription vendeur'), ('signup_client', 'Inscription client'), ('page_view', 'Page vue'), ('product_view', 'Vue produit'), ('order_placed', 'Commande passée'), ('payment', 'Paiement'), ('product_add', 'Ajout produit'), ('product_edit', 'Modification produit'), ('product_delete', 'Suppression produit'), ('admin_action', 'Action admin')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
