# Generated by Django 5.2.4 on 2026-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_publiciteproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, max_length=300)),
                ('icone', models.CharField(default='🎉', max_length=20)),
                ('cible', models.CharField(choices=[('vendeur', 'Espace vendeur'), ('client', 'Espace client'), ('tous', 'Tout le monde')], default='vendeur', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
