# Generated by Django 5.2.4 on 2026-09-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notifications_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='notifications_email',
            field=models.BooleanField(default=True),
        ),
    ]
