"""
Django settings for marketplace project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge le fichier .env a la racine du projet s'il existe.
# Les variables reellement definies dans l'environnement ou sur le
# dashboard Render ont TOUJOURS priorite : .env ne fait que completer
# ce qui manque en developpement local.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-!)oye@(+2bh+xu=l*t0caci07jv2%sf9w_(%g-ug+e5k7a2c+!'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Pour mise en ligne: mettre 'False' ou utiliser variable d'environnement
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Pour mise en ligne: remplacer par votre domaine
# ex: 'shopy-guinee.com,www.shopy-guinee.com'
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

# Origines HTTPS autorisées (obligatoire derrière un proxy comme Render
# pour que les formulaires de connexion admin/POST fonctionnent en production)
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}'
    for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1')
]

# ============================================
# CONFIGURATION EMAIL/SMTP
# ============================================
# Serveur SMTP pour envoi des emails transactionnels
# Pour Gmail: smtp.gmail.com (port 587, TLS)
# Pour SendMail: localhost
# Pour Mailgun: smtp.mailgun.org

# Utiliser console en DEV, SMTP en PROD
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  # Votre email
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # Votre mot de passe app
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@shopy-guinee.com')

# Email de contact pour les pages légales
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'support@shopy-guinee.com')

# URL publique du site : utilisee pour construire les liens cliquables
# dans les e-mails (confirmation de compte, code de verification...).
# En local, laisser vide : les emails resteront sans lien.
SITE_URL = os.environ.get('SITE_URL', '')

# ============================================
# AFFICHAGE PERSONNALISE DE LA PAGE D'ACCUEIL
# ============================================
# False = les 4 cartes (Acheter / Vendre / Connexion Vendeur /
#          Mon Compte) restent visibles. Pratique en developpement
#          pour tester et verifier chaque parcours en un clic.
# True  = un utilisateur deja inscrit ne voit QUE ce qui le concerne :
#          le client son « Mon Compte », le vendeur son « Mon Espace ».
#          A activer au moment de la mise en production, une fois les
#          tests manuels des 4 parcours termines.
#
# Variable d'environnement pour l'activer sans redemarrer le code :
#   PowerShell : $env:WELCOME_PERSONNALISE="True"
#   Render     : WELCOME_PERSONNALISE = True
WELCOME_PERSONNALISE = os.environ.get(
    'WELCOME_PERSONNALISE', 'False'
).lower() in ('1', 'true', 'yes')

# Pour recevoir les notifications admin
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@shopy-guinee.com')

# ============================================
# RESEND — service d'envoi d'emails
# ============================================
# La cle API n'est JAMAIS ecrite dans le code source : elle est lue
# uniquement depuis la variable d'environnement RESEND_API_KEY.
#   - en local      : fichier .env (ignore par Git, cf. .gitignore)
#   - en production : dashboard Render -> Environment (cf. render.yaml)
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')

# Permet de desactiver l'envoi sans toucher au code (pratique en local).
RESEND_ENABLED = os.environ.get('RESEND_ENABLED', 'True').lower() in ('1', 'true', 'yes')

# Expediteur. En production, RESEND_FROM_EMAIL doit appartenir a un
# domaine verifie sur Resend. Pour un simple test, Resend met a
# disposition l'adresse de onboarding : onboarding@resend.dev
RESEND_FROM_EMAIL = os.environ.get('RESEND_FROM_EMAIL', 'onboarding@resend.dev')
RESEND_FROM_NAME = os.environ.get('RESEND_FROM_NAME', 'SHOPY')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'channels',
    'core'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Fichiers statiques en production
    'core.middleware.SecurityHeadersMiddleware',  # Custom security headers
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RateLimitMiddleware',  # Custom rate limiting
]

ROOT_URLCONF = 'marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # IMPORTANT : indispensable pour la barre de navigation
                # (is_vendeur / is_client / active_url / nb_notifications)
                'core.context_processors.notifications_count',
                'core.context_processors.firebase_config',   # Variables Firebase
                'core.context_processors.support_email',     # Email de support
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace.wsgi.application'

ASGI_APPLICATION = 'marketplace.asgi.application'

# Channel layer configuration
# Pour dev: InMemoryChannelLayer (un seul processus)
# Pour prod: Redis (plusieurs processus) - installer: pip install channels_redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': os.environ.get('CHANNEL_LAYER_BACKEND', 'channels.layers.InMemoryChannelLayer'),
        'CONFIG': {
            'hosts': [
                (os.environ.get('REDIS_HOST', 'localhost'), int(os.environ.get('REDIS_PORT', 6379)))
            ],
        } if os.environ.get('CHANNEL_LAYER_BACKEND') != 'channels.layers.InMemoryChannelLayer' else {},
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Base de données : PostgreSQL en production (Render), SQLite en développement.
#
# ⚠️ IMPORTANT (plan gratuit Render) :
# Le système de fichiers des web services gratuits est ÉPHÉMÈRE : toute donnée
# écrite sur disque (donc SQLite db.sqlite3) est DÉTRUITE à chaque redémarrage,
# redéploiement ou réveil après mise en veille. C'est pour cela que les comptes
# créés « disparaissent » : ils étaient écrits dans SQLite.
# En production, DATABASE_URL (PostgreSQL managé par Render) est donc OBLIGATOIRE.

if not DEBUG:
    _database_url = os.environ.get('DATABASE_URL', '')
    if not _database_url:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "DATABASE_URL est absente en production. Créez la base PostgreSQL "
            "dans Render (Dashboard → New + → PostgreSQL), copiez l'Internal "
            "Database URL, puis ajoutez-la dans le service (Environment → "
            "DATABASE_URL). Sans elle l'application utilise SQLite sur un "
            "disque éphémère et toutes les données disparaissent à chaque "
            "redémarrage (comptes créés puis introuvables)."
        )

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR}/db.sqlite3',
        # Reutilisation de la connexion pendant 10 minutes : evite
        # d'ouvrir/fermer une connexion a chaque requete.
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', 600)),
        conn_health_checks=True,
    )
}

# Borne le nombre de connexions simultanees par worker.
# Sans maxconn, 1000 visiteurs connectes en meme temps peuvent epuiser
# le pool PostgreSQL et faire tomber tout le site. 20 x 2 workers =
# 40 connexions maxi : tres en dessous des limites d'un plan gratuit.
#
# `maxconn` est une option psycopg2 (PostgreSQL) uniquement : l'appliquer
# a SQLite leve "TypeError: maxconn is an invalid keyword argument"
# et empeche meme le demarrage du serveur en developpement local.
if DATABASES['default'].get('ENGINE', '').endswith('postgresql'):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['maxconn'] = int(
        os.environ.get('DB_MAX_CONN', 20)
    )

# ============================================
# CACHE
# ============================================
# Objectif : absorber les lectures repetees (catalogue, pages produits)
# qui allaient actuellement a la base a chaque affichage.
#
# Backend cache fichier en repli : aucune dependance externe a
# installer. Si REDIS_URL est fourni (Render ou service externe),
# Redis est automatiquement utilise, sans toucher au code.
CACHE_REDIS_URL = os.environ.get('REDIS_URL', '').strip()

if CACHE_REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CACHE_REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    # Repli multi-processus sans dependance : cache sur disque.
    # Plus lent que Redis mais toujours bien plus rapide qu'un SELECT.
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': os.path.join(BASE_DIR, 'media', 'shopy_cache'),
            'TIMEOUT': 300,
        }
    }

# ============================================
# SESSIONS
# ============================================
# Les sessions en base ecrivent une ligne SQL par page affichee.
# Avec 1000 visiteurs connectes en meme temps, cela inonde
# inutilement PostgreSQL. Le cache les stocke hors base.
#
# Le comportement reste identique (y compris la deconnexion) :
# seul le support de stockage change.
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'core/static'),
    BASE_DIR / 'static',
]

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise : compression et cache des fichiers statiques en production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

LOGIN_REDIRECT_URL = 'dashboard_vendeur'
# Page de connexion client (par défaut)
LOGIN_URL = 'connexion_client'

# ============================================
# SECURITY HEADERS
# ============================================
# Cookies sécurisés
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Content Security Policy (CSP) - Empêche XSS et injections
# Nota: À ajuster selon les besoins JS de l'application
SECURE_CONTENT_SECURITY_POLICY = {
    "default-src": "'self'",
    "img-src": "'self' data: https:",
    "style-src": "'self' 'unsafe-inline'",
    "script-src": "'self' 'unsafe-inline'",
    "font-src": "'self'",
    "connect-src": "'self' ws: wss:",
    "frame-ancestors": "'none'",
}

# Permissions Policy - Contrôle des fonctionnalités navigateur
SECURE_PERMISSIONS_POLICY = {
    'camera': '()',
    'microphone': '()',
    'geolocation': '()',
    'payment': '()',
}

# ============================================
# FILE UPLOAD SECURITY
# ============================================
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Extensions autorisées pour les uploads
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']
ALLOWED_DOCUMENT_EXTENSIONS = ['.pdf', '.doc', '.docx']

# Taille maximale par fichier (5MB)
FILE_MAX_SIZE = 5 * 1024 * 1024

# ============================================
# FIREBASE CONFIGURATION (pour notifications push)
# Ces valeurs doivent être définies dans les variables d'environnement
# ============================================
FIREBASE_API_KEY = os.environ.get('FIREBASE_API_KEY', '')
FIREBASE_AUTH_DOMAIN = os.environ.get('FIREBASE_AUTH_DOMAIN', '')
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')
FIREBASE_STORAGE_BUCKET = os.environ.get('FIREBASE_STORAGE_BUCKET', '')
FIREBASE_SENDER_ID = os.environ.get('FIREBASE_SENDER_ID', '')
FIREBASE_APP_ID = os.environ.get('FIREBASE_APP_ID', '')

# NOTE : la configuration TEMPLATES (y compris les context processors Firebase)
# se trouve une seule fois plus haut dans ce fichier.
